### ISSUE TITLE
KeyError for `branch` in build_commit_history.py bug

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/wp2.2_dev#30]
**How to reproduce:** Run `start.py` from the `master` branch against this repository, i.e. `wp2.2_dev`.

**Symptom:** There is a KeyError for the key `branch` in `build_commit_history.py`. Here is the traceback:

```
Finding forks of OPEN-NEXT/wp2.2_dev page 1
There are 1 forks of OPEN-NEXT/wp2.2_dev
retrieving commits in OPEN-NEXT/wp2.2_dev
fetching info at https://github.com/OPEN-NEXT/wp2.2_dev
Traceback (most recent call last):
  File "/home/penyuan/.vscode-oss/extensions/ms-python.python-2020.5.86806/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/penyuan/.vscode-oss/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/penyuan/.vscode-oss/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/penyuan/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/penyuan/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/penyuan/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/penyuan/devel/git/wp2.2_dev/src/start.py", line 174, in <module>
    main()
  File "/home/penyuan/devel/git/wp2.2_dev/src/start.py", line 116, in main
    build_commit_history(known_commits, commit_history)
  File "/home/penyuan/devel/git/wp2.2_dev/src/build_commit_history.py", line 115, in build_commit_history
    colour = palette_html[branch_names.index(commit_history.nodes[commit]['branch'])]
KeyError: 'branch'
fish: “env PYTHONIOENCODING=UTF-8 PYTH…” terminated by signal SIGTERM (Polite quit request)
```

**Comment by jbon** [comment]
I cannot reproduce from `master` branch at c4359de9. The commit history of OPEN-NEXT/wp2.2_dev is successfully generated and colorized. This may be due to the fact that some commits have been made in the repo in the meantime. Probably, the thing that created the error disappeared. We'll need to find another case to investigate this bug.

**Comment by penyuan** [comment]
> This may be due to the fact that some commits have been made in the repo in the meantime. Probably, the thing that created the error disappeared.

That's probably the case. I think we will just have to keep an eye out for this happening again, and try to catch it then.

**Comment by penyuan** [comment]
Current implementation in `main` branch doesn't have this issue. Closing for now.
